providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["rm -rf dist", "npm run build:railway"]

[start]
cmd = "npm run start"

[variables]
NODE_ENV = "production"