providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build:railway"]

[start]
cmd = "npm run start"

[variables]
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "production"