[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd apps/web && npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd apps/web && npm run build"]

[start]
cmd = "cd apps/web && npm run start"

[variables]
NODE_ENV = "production"