#!/bin/bash
# AUTOMATED MARKDOWN UPDATE SCRIPT
# Generated by markdown-consistency-auditor.cjs

echo "🚀 Updating markdown documentation for schema consistency..."

# Update logs table references
find . -name "*.md" -exec sed -i '' 's/logs table/checklist_items table/g' {} +
find . -name "*.md" -exec sed -i '' "s/\.from('logs')/\.from('checklist_items')/g" {} +
find . -name "*.md" -exec sed -i '' "s/\.from("logs")/\.from('checklist_items')/g" {} +

# Update field name references  
find . -name "*.md" -exec sed -i '' 's/property_name/name/g' {} +
find . -name "*.md" -exec sed -i '' 's/street_address/address/g' {} +

# Update property_id type documentation
find . -name "*.md" -exec sed -i '' 's/property_id: number/property_id: string (UUID)/g' {} +
find . -name "*.md" -exec sed -i '' 's/property_id.*integer/property_id: UUID string/g' {} +

echo "✅ Markdown documentation updated"
echo "🔍 Run 'node markdown-consistency-auditor.cjs' to verify updates"
