// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://urrydhjchgxnhyggqtzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVycnlkaGpjaGd4bmh5Z2dxdHpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyODM2NjAsImV4cCI6MjA2NTg1OTY2MH0.IrtFxZzLLjxUOfpOrt5Llw8EnyvuWI6WDOuvsvFDFaM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);